### ISSUE TITLE
Support for step attribute on inputs of type number

### ISSUE THREAD

**Issue by stumacsolutions** [pioto/html5valdialect#1]
Hi there. First off I would just like to say that this a cracking library which provides a lot of value for very little effort.

I was wondering if it would make sense for the DigitsPerformer class to set the 'step' html attribute? It currently sets the 'pattern' attribute.

I am experimenting with using Thymeleaf templates on the server, generating html 5 validation attributes using this library, and then on the front end using the bootstrap validation framework to provide client side validation. Without the step attribute, bootstrap validation will only allow whole numbers, whereas I want to have numbers with 2 decimal places, which I have modelled using the @Digits annotation.

One thing that I did try was to register my own DigitsPerformer implementation with the Html5ValDialect, but this gets ignored because the ValidationPerformerFactory returns the first match, which is the default one for the @Digits annotation.

**Comment by pioto** [comment]
Hi,

I didn't remember even forking this from Sourceforge... I think I tried it out a bit and it didn't meet my needs.

You should probably follow up with the upstream project for any changes; I'm not planning any myself.

**Comment by stumacsolutions** [comment]
Ahhh that's why there were no issues or activity on the project. I didn't
spot that it was a fork. Will check more closely next time :)

Thanks and happy new year.

Stuart
